[package]
name = "argwerk"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["argument", "cli", "arg", "parser", "parse"]
categories = ["command-line-interface"]
repository = "https://github.com/udoprog/async-fuse"
homepage = "https://github.com/udoprog/async-fuse"
documentation = "https://docs.rs/async-fuse"
description = """
Helpers for fusing asynchronous computations.
"""
