[package]
name = "builder"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[dependencies]
anyhow = "1.0.37"
toml = "0.5.8"
serde = { version = "1.0.118", features = ["derive"] }
